name: Docker Image CI2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekeando codigo 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}      #SI SE GENERA UN TOKEN PARA LOGUEARSE EN DOCKER
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  #contraseña del token
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    #- name: Build the Docker image
      
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
